### ISSUE TITLE
walk fails when trying to open a symbolic link

### ISSUE THREAD

**Issue by tdjones** [yui/shifter#136]
checkDirectory is using fs.statSync to get stat, but that method throws an error when you pass it the path to a symbolic link.

> fs.js:689
>   return binding.stat(pathModule._makeLong(path));
>                  ^
> Error: ENOENT, no such file or directory '/project/favicon.ico'
>     at Object.fs.statSync (fs.js:689:18)
>     at /project/node_modules/shifter/lib/walk.js:122:39
>     at /project/node_modules/shifter/lib/stack.js:24:38
>     at Object.cb [as oncomplete] (fs.js:168:19)

**Comment by tdjones** [comment]
just realized this was actually due to a broken symlink.
